@startuml asset_base

' left to right direction
top to bottom direction

' Class definitions

package "Common" {

    abstract       Common {
        +id : int
        +name : str
    }

}

package "Entities" {

    abstract    Entity {
        +domicile : Domicile
        +asset_list : Asset[0..*]
    }

    abstract    Institution

    class       Issuer {
        +share_list : Share[0..*]
    }

    class       Exchange {
        +mic : ISO 10383
        +listing_list : Listed[0..*]
    }

    class       Domicile {
        +country_code : ISO 3166-1
        +country_name : ISO 3166-1
        +currency : Currency
        +entity_list : Entity[0..*]
    }

    class       Currency {
        +ticker : ISO 4217 3-letter
        +name : Official name
    }

    ' Common inheritance
    Common.Common <|-- Entity

    ' Domicile and Currency
    Currency "1" --* "*" Domicile : < denominates
    Domicile "1" -r-* "*" Entity : < domiciled

    ' Entities
    Entity <|-- Institution
    Institution <|-- Exchange
    Institution <|-- Issuer

}

package "Assets" {

    abstract    AssetBase {
        +currency : Currency
        -_time_series_single_item : TimeSeriesBase
    }

    abstract    Asset {
        +owner : Entity
    }

    abstract    Share {
        +issuer : Issuer
    }

    abstract    Listed {
        +ticker : str
        +isin : ISIN number
        +exchange : Exchange
    }

    class       ListedEquity {
        -_dividend_series : Dividend
    }

    class       ETF {
        +index : Index
    }

    class       Cash {
    }

    class       Forex {
        +currency2 : Currency
    }

    class Index {
    }

    ' Common inheritance
    Common.Common <|-- AssetBase

    ' Assets
    AssetBase <|-- Asset
    AssetBase <|-- Index
    Asset <|-- Share
    Asset <|-- Cash
    Cash <|-- Forex
    Share <|-- Listed
    Listed <|-- ListedEquity
    ListedEquity <|-- ETF

}

package "Time Series" {

    class TimeSeriesBase {
        +date_stamp : date
        +_base_obj : AssetBase
    }

    class EODBase {
        +price : float
    }

    class TradeEOD {
        +open : float
        +close : float
        +high : float
        +low : float
        +adjusted_close : float
        +volume : float

    }

    class ListedEOD {
    }

    class ForexEOD {
    }

    class IndexEOD {
    }

    class Dividend {
        +listed_equity : ListedEquity
        +currency : str
        +declaration_date : datetime.date
        +payment_date L datetime.date
        +period : str
        +record_date : datetime.date
        +unadjusted_value : float
        +adjusted_value : float
    }

    ' Time Series
    TimeSeriesBase <|-- EODBase
    EODBase <|-- TradeEOD
    TradeEOD <|-- ListedEOD
    TradeEOD <|-- ForexEOD
    TradeEOD <|-- IndexEOD
    TimeSeriesBase <|-- Dividend

}

package "Accounts" {

    class CashAccount

    class SettlementAccount

    Assets.Cash <|-- CashAccount
    Assets.Cash <|-- SettlementAccount

}

' Pricing
Currency "1" --* "1" AssetBase : < priced in currency

' Entities to Assets relationships
Entity "1" *-- "*" Asset : > owns
Issuer "1" -l-* "*" Share : > issues
Exchange "1" -l-* "*" Listed : > lists

' Asset to Asset relationships
ETF "*" *-r- "1" Assets.Index : > replicates

' Asset to Time Series relationships
AssetBase "1" *-- "*" TimeSeriesBase : > acquires

@enduml