version: 1

directories:
  working:
    cache: "~/.local/var/cache"
    log: "~/.local/var/log"
    tmp: "~/.local/var/tmp"

backends:
  database:
    mysql:
      asset_base: "mysql://justin:future@localhost/%s?unix_socket=/var/run/mysqld/mysqld.sock"
      history: "mysql://justin:future@localhost/%s?unix_socket=/var/run/mysqld/mysqld.sock"
